benutzerDB/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from rest_framework.documentation import include_docs_urls
from rest_framework import mixins
from django.contrib.auth import views as auth_views
from userDB.models import *


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username')


class SSHKeySerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = SSHKey
        fields = ('profile', 'key', 'key_type', 'hash_md5')

    hash_md5 = serializers.CharField(max_length=47, read_only=True)
    key_type = serializers.CharField(max_length=30, read_only=True)


class MACAddressSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = MACAddress
        fields = ('profile', 'mac', 'hostname')


class ProfileSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Profile
        fields = ('user', 'ssh_keys', 'mac_addresses')

    user = UserSerializer()
    ssh_keys = SSHKeySerializer(many=True)
    mac_addresses = MACAddressSerializer(many=True)


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class ProfileViewSet(mixins.UpdateModelMixin,
                     mixins.RetrieveModelMixin,
                     mixins.ListModelMixin,
                     viewsets.GenericViewSet):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer


class SSHKeyViewSet(viewsets.ModelViewSet):
    queryset = SSHKey.objects.all()
    serializer_class = SSHKeySerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'sshkeys', SSHKeyViewSet)
router.register(r'profiles', ProfileViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^docs/', include_docs_urls(title="RaumZeitPanel API")),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'accounts/login/', auth_views.LoginView.as_view(), name="login"),
    url(r'accounts/logout/', auth_views.logout_then_login, name="logout"),
    url(r'^', include('userDB.urls')),
]

userDB/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^i18n/setlang/(?P<language>[a-zA-Z\-]+)/', views.switch_language,
        name='switch-language'),
    url('ssh/add/', views.SSHKeyCreate.as_view(), name='ssh-keys-add'),
    url('ssh/(?P<pk>[0-9]+)/delete/', views.SSHKeyDelete.as_view(),
        name='ssh-keys-delete'),
    url('ssh/', views.SSHKeyView.as_view(), name='ssh-keys-list'),
    url('mac/add/', views.MACAddressCreate.as_view(), name='mac-addresses-add'),
    url('mac/(?P<pk>[0-9]+)/delete/', views.MACAddressDelete.as_view(),
        name='mac-addresses-delete'),
    url('mac/', views.MACAddressView.as_view(), name='mac-addresses-list'),
    url('pin/', views.pin_detail, name='pin-detail'),
    # compatibility with old BenutzerDB
    url(r'BenutzerDB/pins/', views.pinpad_pinlist, name='pinpad-pinlist'),
]

userDB/models.py
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.dispatch import receiver
from macaddress.fields import MACAddressField
import sshpubkeys
import random


class Profile(models.Model):
    """Stores additional user information.

    Every User has a Profile attached that stores extra information. While we
    could also extend the User model, this is overkill for our use case.

    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Whether or not this User is a member of the RaumZeitLabor e.V. This must
    # only be settable by administrators (the NOC) or board members (the
    # Vorstand).
    member = models.BooleanField(default=False, blank=True,
                                 verbose_name=_('Member'))

    # The PIN for accessing the room. This must be a 6 digit number.
    pin = models.PositiveSmallIntegerField(
        null=True, verbose_name=_('PIN'),
        help_text=_('Will be automatically generated if user is set as member'))

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ['user__username']
        verbose_name = _('profile')
        verbose_name_plural = _('profiles')

    def save(self, *args, **kwargs):
        # automatically generate PIN if the user is a member
        if self.member:
            self.pin = random.randint(10**5, (10**6)-1)
        super().save(*args, **kwargs)


class MACAddress(models.Model):
    """Stores a MAC address for a given host, associated with a user.

    A user can have multiple MAC addresses associated with them.
    """
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE,
                                related_name='mac_addresses')
    mac = MACAddressField(blank=False)
    hostname = models.CharField(max_length=32)
    vendor = models.CharField(max_length=32)

    def __str__(self):
        return self.profile.user.username

    class Meta:
        ordering = ['profile__user__username']
        verbose_name = _('MAC address')
        verbose_name_plural = _('MAC addresses')


# Whenever a User object is created, create a Profile for it.
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


# Whenever a User object is modified, also save its Profile.
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


def ssh_key_validator(key):
    try:
        ssh = sshpubkeys.SSHKey(key)
        ssh.parse()
    except sshpubkeys.MalformedDataError:
        raise ValidationError("Invalid SSH key.")


class SSHKey(models.Model):
    """Stores an SSH public key that can be used to unlock the door."""
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE,
                                related_name='ssh_keys')

    name = models.CharField(max_length=200, verbose_name=_('Name'))
    key = models.TextField(validators=[ssh_key_validator],
                           verbose_name=_('SSH key'))

    key_type = models.CharField(max_length=30, verbose_name=_('Key type'))

    hash_md5 = models.CharField(
        max_length=47, verbose_name=_('MD5 hash'),
        help_text=_('Automatically generated hash of the key'))

    def __str__(self):
        return self.hash_md5

    class Meta:
        ordering = ['hash_md5']
        verbose_name = _('SSH key')
        verbose_name_plural = _('SSH keys')


@receiver(pre_save, sender=SSHKey)
def create_pin(sender, instance, **kwargs):
    if not instance.hash_md5 or not instance.key_type:
        ssh = sshpubkeys.SSHKey(instance.key)
        ssh.parse()
        instance.hash_md5 = ssh.hash_md5()[4:]
        #instance.key_type = instance.key.strip().split()[0][4:]
        instance.key_type = ssh.key_type.decode()
        instance.key = ssh.keydata.rstrip(ssh.comment).strip()

userDB/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView
from django.utils.translation import LANGUAGE_SESSION_KEY
from django.utils.decorators import method_decorator
from django.core.exceptions import ValidationError
from django.utils import translation
from django.urls import reverse_lazy
from django.conf import settings
from django.shortcuts import render
import urllib
import ipaddress
import requests
import json
from . import models


@login_required
def index(request):
    return render(request, "index.html")

@user_passes_test(lambda u: u.is_superuser)
def pinpad_pinlist(request):
    '''List all pins.

    This view is only meant to be used by the Pinpad and exists for
    compatibility with the old BenutzerDB. It should eventually be removed once
    the Pinpad has been migrated to use the new API.
    '''
    members = models.Profile.objects.filter(member=True)
    pinlist = [{"handle": member.user.get_username(), "pin": str(member.pin)}
               for member in members]
    # The JSON should be sorted to ensure that the CRC which is calculated by
    # the pinpad-controller on every sync  does not change if no PINs have
    # changed.
    data = json.dumps(pinlist, sort_keys=True)
    return HttpResponse(data, content_type='application/json')


@method_decorator(login_required, name='dispatch')
class SSHKeyView(ListView):
    template_name = 'sshkey_list.html'

    def get_queryset(self):
        return models.SSHKey.objects.filter(profile=self.request.user.profile)


@method_decorator(login_required, name='dispatch')
class SSHKeyCreate(CreateView):
    model = models.SSHKey
    fields = ['name', 'key']
    template_name = 'sshkey_form.html'
    success_url = reverse_lazy('ssh-keys-list')

    def form_valid(self, form):
        form.instance.profile_id = self.request.user.profile.id
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class SSHKeyDelete(DeleteView):
    success_url = reverse_lazy('ssh-keys-list')
    template_name = 'sshkey_confirm_delete.html'

    def get_queryset(self):
        return models.SSHKey.objects.filter(profile=self.request.user.profile)


@method_decorator(login_required, name='dispatch')
class MACAddressView(ListView):
    template_name = 'macaddress_list.html'

    def get_queryset(self):
        return models.MACAddress.objects.filter(profile=self.request.user.profile)


def get_ip_details(ip):
    # FIXME: Error handling
    api_base = getattr(settings, 'UNIFI_CONTROLLER_HOST')
    api_login = {
        'username': getattr(settings, 'UNIFI_CONTROLLER_USER'),
        'password': getattr(settings, 'UNIFI_CONTROLLER_PASS'),
    }

    if not all((api_base, api_login['username'], api_login['password'])):
        return None

    s = requests.Session()
    s.headers.update({'User-Agent': 'benutzerdb2'})
    s.verify = False

    try:
        r = s.post('{}/api/login'.format(api_base), json=api_login)
        r.raise_for_status()
        r = s.get('{}/api/s/default/stat/sta'.format(api_base))
        r.raise_for_status()
    except requests.exceptions.RequestException:
        return None

    clients = r.json()
    clients = list(filter(lambda c: c['ip'] == ip, clients['data']))

    if not clients or len(clients) > 1:
        return None

    return clients[0]


@method_decorator(login_required, name='dispatch')
class MACAddressCreate(CreateView):
    model = models.MACAddress
    fields = ['hostname']
    template_name = 'macaddress_form.html'
    success_url = reverse_lazy('mac-addresses-list')

    def form_valid(self, form):
        form.instance.profile_id = self.request.user.profile.id
        client_ip = self.request.META.get('REMOTE_ADDR')

        if not ipaddress.ip_address(client_ip) in ipaddress.ip_network('172.22.36.0/23'):
            raise ValidationError(_('You need to be in one of the RaumZeitLabor wifi networks to add your MAC address.'))

        client = get_ip_details(client_ip)
        if not client:
            return ValidationError('Could not find client in Ubiquiti controller API json')

        form.instance.mac = client['mac']
        form.instance.vendor = client['oui']
        return super().form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        client_ip = self.request.META.get('REMOTE_ADDR')
        client = get_ip_details(client_ip)

        if client:
            context['ubiquiti_client'] = client

        return context


@method_decorator(login_required, name='dispatch')
class MACAddressDelete(DeleteView):
    success_url = reverse_lazy('mac-addresses-list')
    template_name = 'macaddress_confirm_delete.html'

    def get_queryset(self):
        return models.MACAddress.objects.filter(profile=self.request.user.profile)

def pin_detail(request):
    return render(request, template_name='pin.html')


def switch_language(request, language):
    response = HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

    if hasattr(request, 'session'):
        request.session[LANGUAGE_SESSION_KEY] = language
    else:
        response.set_cookie(
            settings.LANGUAGE_COOKIE_NAME, language,
            max_age=settings.LANGUAGE_COOKIE_AGE,
            path=settings.LANGUAGE_COOKIE_PATH,
            domain=settings.LANGUAGE_COOKIE_DOMAIN,
            )
    return response

userDB/templates/base.html
{% load static %}
{% load gravatar %}
{% load i18n %}

<!doctype html>
<html lang='{{ request.LANGUAGE_CODE }}'>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RaumZeitPanel</title>

    <link rel="shortcut icon" href="{% static 'img/rzl-logo.svg' %}" />

    {% block css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--<link href='https://fonts.googleapis.com/css?family=Fira+Sans:400,500,800' rel='stylesheet' type='text/css'>-->
    <link href='{% static "css/style.css" %}' rel='stylesheet' type='text/css'>
    {% endblock %}
</head>

<body>

    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'img/rzl-logo.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            RaumZeitPanel
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active"><a class="nav-link" href="{% url 'index' %}">{% trans 'Home' %} <span class="sr-only">(current)</span></a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'pin-detail' %}">{% trans 'PIN' %}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'mac-addresses-list' %}">{% trans 'MAC addresses' %}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'ssh-keys-list' %}">{% trans 'SSH' %}</a></li>
            </ul>
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.LANGUAGE_CODE|language_name }}</a>
                     <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            {% if language.code != request.LANGUAGE_CODE %}
                                <a class="dropdown-item" href='{% url 'switch-language' language=language.code %}'>{{ language.name_local }}</a>
                            {% endif %}
                        {% endfor %}
                     </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="{% gravatar_url user.email 30 %}" width="30" height="30" class="d-inline-block align-top gravatar" alt="Gravatar icon for {{ user.username }}">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">{% trans 'Change password' %}</a>
                        {% if user.is_staff %}
                            <a class="dropdown-item" href="{% url 'admin:index' %}">{% trans 'Admin' %}</a>
                        {% endif %}

                        <a class="dropdown-item" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    {% endblock navbar %}

    <div role="main" class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

userDB/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class='row'>
	<div class='col-12'>
		<h1>{% blocktrans with name=user.username %}Hello {{ name }}{% endblocktrans %}</h1>

		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus laboriosam inventore mollitia, facere, voluptates ipsa pariatur deserunt voluptatibus minima similique nam officia perferendis dignissimos ex repellendus suscipit doloremque, deleniti modi.
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta aspernatur natus, alias ullam dolorum dolor repellat ducimus, fuga asperiores quod, ea impedit obcaecati doloremque. Laborum deserunt aliquid doloribus ut voluptates!
	</div>
</div>
{% endblock %}

userDB/templates/macaddress_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap4 %}

{% block content %}
<div class='row'>
	<div class='col-md-6'>
		<h1>{% trans 'Delete MAC address' %}</h1>

		<form method="POST">
			{% csrf_token %}
			<p>{% blocktrans with key=object %}Are you sure you want to delete the MAC address {{ key }}?{% endblocktrans %}</p>

			<button class="btn btn-lg btn-primary btn-block" type="submit">{% trans 'Yes, delete' %}</button>
		</form>
	</div>
</div>
{% endblock %}

userDB/templates/macaddress_form.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap4 %}

{% block content %}
<div class='row'>
	<div class='col-md-6'>
		<h1>{% trans 'Add MAC address' %}</h1>

		<form method="POST">
			{% csrf_token %}

			{% if ubiquiti_client %}
				<p>{% blocktrans with mac=ubiquiti_client.mac oui=ubiquiti_client.oui essid=ubiquiti_client.essid  %}Do you want to associate the device with MAC address <strong>{{ mac }}</strong> ({{ oui }}), connected to WiFi network <strong>{{ essid }}</strong> with your account?{% endblocktrans %}</p>

				<div class="form-group"><label for="id_hostname">Hostname</label><input type="text" name="hostname" maxlength="32" class="form-control" placeholder="Hostname" title="" required id="id_hostname" value="{{ ubiquiti_client.hostname }}" /></div>

				<button class="btn btn-lg btn-primary btn-block" type="submit">{% trans 'Associate MAC' %}</button>
			{% else %}
				<p>{% trans "Could not fetch client details. Please ensure you're connected to the internal WiFi network and are connected to the panel using the internal hostname." %}</p>
			{% endif %}

		</form>
	</div>
</div>
{% endblock %}

userDB/templates/macaddress_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class='row'>
	<div class='col-12'>
		<a href="{% url 'mac-addresses-add' %}" class="btn btn-primary float-right">{% trans 'Add MAC address' %}</a>
		<h1>{% trans 'MAC addresses' %}</h1>

		<p>{% trans "If you add your devices' MAC addresses, you will automatically be listed as present on the status pages if you are connected to one of the WiFi networks." %}</p>

		<table class="table table-striped">
			<thead>
				<tr>
					<th scope="col">Hostname</th>
					<th scope="col">MAC</th>
					<th scope="col">Vendor</th>
					<th scope="col">&nbsp;</th>
				</tr>
			</thead>
			<tbody>
				{% for mac in macaddress_list %}
					<tr>
						<td>{{ mac.hostname }}</td>
						<td>{{ mac.mac }}</td>
						<td>{{ mac.vendor }}</td>
						<td><a href="{% url 'mac-addresses-delete' mac.pk %}">Delete</a></td>
					</tr>
				{% empty %}
					{% url 'mac-addresses-add' as add_url %}
					<tr><td colspan="4">{% blocktrans %}You don't seem to have any MAC addresses at the moment. You can <a href="{{ add_url }}">add one</a>.{% endblocktrans %}</td></tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

userDB/templates/pin.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap4 %}

{% block content %}
<div class='row'>
	<div class='col-md-12'>
		<a href='' class='btn btn-danger float-right'>{% trans 'Generate new PIN' %}</a>
		<h1>{% trans 'PIN' %}</h1>
		{% if user.profile.member %}
			<p>{% trans 'This is your PIN. You can use it to unlock the main door. Please make sure to keep it secret.' %}
			<p class='pin'>{{ user.profile.pin }}</p>
			<p><small>({% trans 'Hover to show' %})</small></p>
		{% else %}
			<p>{% trans "You don't seem to have a PIN or your profile does not have the 'member' flag set." %}</p>
			<p>{% trans "Please make sure your profile details are correct and ask the board to confirm your membership status. A PIN will then be generated automatically." %}</p>
		{% endif %}
	</div>
</div>
{% endblock %}

userDB/templates/sshkey_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap4 %}

{% block content %}
<div class='row'>
	<div class='col-md-6'>
		<h1>{% trans 'Delete SSH key' %}</h1>

		<form method="POST">
			{% csrf_token %}
			<p>{% blocktrans with key=object %}Are you sure you want to delete the key {{ key }}?{% endblocktrans %}</p>

			<button class="btn btn-lg btn-primary btn-block" type="submit">{% trans 'Yes, delete' %}</button>
		</form>
	</div>
</div>
{% endblock %}

userDB/templates/sshkey_form.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap4 %}

{% block content %}
<div class='row'>
	<div class='col-md-6'>
		<h1>{% trans 'Add SSH key' %}</h1>

		<form method="POST">
			{% csrf_token %}

			{% bootstrap_form form %}

			<button class="btn btn-lg btn-primary btn-block" type="submit">{% trans 'Add key' %}</button>
		</form>
	</div>
</div>
{% endblock %}

userDB/templates/sshkey_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class='row'>
	<div class='col-12'>
		<a href="{% url 'ssh-keys-add' %}" class="btn btn-primary float-right">{% trans 'Add SSH key' %}</a>
		<h1>{% trans 'SSH keys' %}</h1>

		<p>{% blocktrans %}These SSH keys can be used to unlock the room door using <code>ssh tuer@tuer.rzl.so -p 2322</code> .{% endblocktrans %}</p>

		<table class="table table-striped">
			<thead>
				<tr>
					<th scope="col">Name</th>
					<th scope="col">Type</th>
					<th scope="col">Hash</th>
					<th scope="col">&nbsp;</th>
				</tr>
			</thead>
			<tbody>
				{% for key in sshkey_list %}
					<tr>
						<td>{{ key.name }}</td>
						<td>{{ key.key_type }}</td>
						<td>{{ key.hash_md5 }}</td>
						<td><a href="{% url 'ssh-keys-delete' key.pk %}">Delete</a></td>
					</tr>
				{% empty %}
					{% url 'ssh-keys-add' as add_url %}
					<tr><td colspan="4">{% blocktrans %}You don't seem to have any SSH keys at the moment. You can <a href="{{ add_url }}">add one</a>.{% endblocktrans %}</td></tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}